config/routes.rb
RedT::Application.routes.draw do

resources :users 
resources :links

get '/', to: 'links#index'

get '/login', to: 'sessions#new'
get '/logout', to: 'sessions#destroy'

post '/sessions', to: 'sessions#create'

end

app/models/link.rb
class Link < ActiveRecord::Base

	belongs_to :user
	
	validates :url, uniqueness: true
	validates :title, :body, presence: true
	validates :score, numericality: {only_integer: true}


end

app/models/user.rb
class User < ActiveRecord::Base

	has_secure_password
	has_many :links, dependent: :destroy
	
	validates :email, uniqueness: true
	validates :name, :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

	def current_user
	    if session[:user_id]
	      return User.find(session[:user_id])
	    end
	end

	def require_authentication
    	redirect_to login_path unless current_user
  	end


end

app/controllers/links_controller.rb
class LinksController < ApplicationController



	def index
		@links = Link.all
	end

	def new
		@link = Link.new
	end

	def create
		@link = Link.new(link_params)
		@link.user = current_user
		@link.score = 0
		@link.date = Date.today
		if @link.save
			redirect_to @link
		end
	end

	def edit
		@link = Link.find(params[:id])
	end

	def show
		@link = Link.find(params[:id])
	end

	def update
		@link = Link.find(params[:id])
		@link.update!(link_params)
		redirect_to @link
	end

	def destroy
		@link = Link.find(params[:id])
		@link.destroy
		redirect_to links_path
	end

	private
	def link_params
		params.require(:link).permit(:title, :body, :url)
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to users_path
  end
  


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :require_authentication, only: [:edit, :update, :destroy]

def index
	@users = User.all
end

def show
	@user = User.find(params[:id])
end

def new
	@user = User.new
end

def create
	@user = User.create(user_params)
	if @user.save 
		redirect_to @user
	else
		render 'new'
	end
end

def edit
	@user = User.find(params[:id])
end

def update
	@user = User.find(params[:id])
	@user.update(user_params)
	if @user.save 
		redirect_to @user
	else
		render 'edit'
	end
end

def destroy
	@user = User.find(params[:id])
	@user.destroy
	redirect_to logout_path
end



private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedT</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%if current_user %>
<%= link_to "Logout", logout_path %>
<%= link_to "New Link", new_link_path %>
<% else  %>
<%= link_to "Create Account", new_user_path %>
<%= link_to "Login", login_path %>

<% end %>
<%= link_to "All Links", links_path %>
<%= link_to "All Users", users_path %>


<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link do |f| %>

<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.label :url %>
<%= f.text_field :url %>

<%= f.submit %>

<% end %>

app/views/links/edit.html.erb
<%= render 'form' %>

<% if current_user == @link.user %>

	<%= form_tag(link_path, method: "delete") do %>
	<%= submit_tag("Delete your link forever") %>
	<% end %>

<% end %>

app/views/links/index.html.erb
<h1>ALL THE LINKS</h1>

<ul>
<% @links.each do |link| %>

<li><%= link_to link.title, link %></li>

	<% end %>
</ul>

app/views/links/new.html.erb
<%= render 'form' %>

app/views/links/show.html.erb
<h1><%= link_to @link.title, "#{@link.url}" %></h1>
<br>by: <%= link_to @link.user.name, @link.user %> on: <%= @link.date %>
<p><%= @link.body %></a>

	<% if @link.user == current_user %>
	<%= link_to "edit", edit_link_path %>
	<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<%= f.label :name %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>

<%= f.submit %>

<% end %>

app/views/users/edit.html.erb
<h3>Edit <%= @user.name %></h3>


<%= render 'form' %>


<% if current_user == @user %>

	<%= form_tag(user_path, method: "delete") do %>
	<%= submit_tag("Delete your account forever") %>
	<% end %>

<% end %>

app/views/users/index.html.erb
<h3>Red.t Users</h3>

<% @users.each do |user| %>
<%= link_to user.name, user %><br>
<%= user.email %><br>
<% end %>

app/views/users/new.html.erb
<h3>Create New User</h3>


<%= render 'form' %>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>


<%= @user.name %>
<%= @user.email %>

<% if current_user == @user %>
	<%= link_to "Edit user", edit_user_path(@user) %>

<ul>
	<% @user.links.each do |link| %>
	<li><%= link_to link.title, link %> </li>
	<% end %>
</ul>


<% end %>